# Generated by Django 5.1.15 on 2026-05-02 16:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slugline', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Script', max_length=255)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('contact', models.TextField(blank=True, default='')),
                ('logline', models.TextField(blank=True, default='')),
                ('synopsis', models.TextField(blank=True, default='')),
                ('written_by_prefix', models.CharField(default='written by', max_length=100)),
                ('content', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(choices=[('scene_heading', 'Scene Heading'), ('action', 'Action'), ('character', 'Character'), ('dialogue', 'Dialogue'), ('parenthetical', 'Parenthetical'), ('transition', 'Transition'), ('shot', 'Shot'), ('extension', 'Extension (V.O./O.S.)')], default='action', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='scripts.scene')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='scripts.script'),
        ),
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('TITLE_CHANGED', 'Title Changed'), ('CONTENT_UPDATED', 'Content Updated'), ('VERSION_SAVED', 'Version Saved'), ('VERSION_RESTORED', 'Version Restored')], max_length=30)),
                ('details', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='scripts.script')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScriptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content_snapshot', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scripts.script')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together={('script', 'order')},
        ),
    ]
