# Generated by Django 5.1.15 on 2026-05-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_script_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='color',
        ),
        migrations.AddField(
            model_name='script',
            name='font_family',
            field=models.CharField(default='Courier Prime', max_length=100),
        ),
        migrations.AddField(
            model_name='script',
            name='paper_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='script',
            name='text_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
