# Generated by Django 5.1.15 on 2026-05-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_remove_script_color_script_font_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='font_family',
            field=models.CharField(blank=True, default='Courier Prime', max_length=100),
        ),
        migrations.AlterField(
            model_name='script',
            name='paper_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='script',
            name='text_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
