# Generated by Django 5.1.15 on 2026-05-03 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_element_pagination_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canvas', to='scripts.script')),
            ],
            options={
                'verbose_name': 'Canvas State',
                'verbose_name_plural': 'Canvas States',
            },
        ),
    ]
