# Generated by Django 5.1.15 on 2026-05-04 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_canvasstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='workspace_edges',
            field=models.JSONField(blank=True, default=list, help_text="Node connections for the Director's Suite"),
        ),
        migrations.CreateModel(
            name='WorkspaceAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(blank=True, default='', help_text='Frontend element UUID for cross-referencing', max_length=128)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('link', 'Link Card'), ('shot', 'Shot Card'), ('idea', 'Idea Block'), ('text', 'Text Block'), ('sticky', 'Sticky Note'), ('mermaid', 'Mermaid Graph')], max_length=20)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=280)),
                ('height', models.FloatField(default=200)),
                ('scale', models.FloatField(default=1.0)),
                ('z_index', models.IntegerField(default=0)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_assets', to='scripts.script')),
            ],
            options={
                'verbose_name': 'Workspace Asset',
                'verbose_name_plural': 'Workspace Assets',
                'ordering': ['z_index'],
            },
        ),
    ]
