# Generated by Django 5.1.15 on 2026-05-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_script_workspace_edges_workspaceasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='font_size',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
