# Generated by Django 5.1.15 on 2026-05-08 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_script_font_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('aspect_ratio', models.CharField(choices=[('16:9', 'Widescreen 16:9'), ('2.39:1', 'Cinemascope 2.39:1'), ('4:3', 'Academy 4:3'), ('1.85:1', 'Flat 1.85:1')], default='16:9', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storyboard', to='scripts.script')),
            ],
            options={
                'verbose_name': 'Storyboard',
                'verbose_name_plural': 'Storyboards',
            },
        ),
        migrations.CreateModel(
            name='SceneCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('shot_number', models.CharField(blank=True, default='', max_length=20)),
                ('scene_heading', models.CharField(blank=True, default='', max_length=255)),
                ('shot_type', models.CharField(blank=True, choices=[('EWS', 'Extreme Wide Shot'), ('WS', 'Wide Shot'), ('FS', 'Full Shot'), ('MWS', 'Medium Wide / Cowboy'), ('MS', 'Medium Shot'), ('MCU', 'Medium Close-Up'), ('CU', 'Close-Up'), ('ECU', 'Extreme Close-Up'), ('INSERT', 'Insert Shot'), ('OTS', 'Over-the-Shoulder'), ('POV', 'Point of View'), ('TWO', 'Two Shot'), ('DUTCH', 'Dutch Angle'), ('AERIAL', 'Aerial Shot'), ('CRANE', 'Crane Shot')], default='MS', max_length=20)),
                ('camera_movement', models.CharField(blank=True, choices=[('static', 'Static'), ('pan_l', 'Pan Left'), ('pan_r', 'Pan Right'), ('tilt_u', 'Tilt Up'), ('tilt_d', 'Tilt Down'), ('dolly_in', 'Dolly In'), ('dolly_out', 'Dolly Out'), ('crane_u', 'Crane Up'), ('crane_d', 'Crane Down'), ('handheld', 'Handheld'), ('steadicam', 'Steadicam'), ('zoom_in', 'Zoom In'), ('zoom_out', 'Zoom Out'), ('arc', 'Arc Shot'), ('whip', 'Whip Pan')], default='static', max_length=20)),
                ('lens', models.CharField(blank=True, default='', max_length=50)),
                ('technical_notes', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='scripts.storyboard')),
            ],
            options={
                'verbose_name': 'Scene Card',
                'verbose_name_plural': 'Scene Cards',
                'ordering': ['order'],
            },
        ),
    ]
