# Generated by Django 5.1.15 on 2026-05-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0009_add_storyboard_scenecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenecard',
            name='aspect_ratio',
            field=models.CharField(blank=True, default='1.78:1', max_length=20),
        ),
        migrations.AddField(
            model_name='scenecard',
            name='height',
            field=models.FloatField(default=500),
        ),
        migrations.AddField(
            model_name='scenecard',
            name='width',
            field=models.FloatField(default=320),
        ),
        migrations.AddField(
            model_name='scenecard',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scenecard',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
