# Generated by Django 5.1.15 on 2026-05-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0010_scenecard_aspect_ratio_scenecard_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='canvas_viewport',
            field=models.JSONField(blank=True, default=dict, help_text="Director's Suite viewport state: {zoom, pan: {x, y}}"),
        ),
        migrations.AddField(
            model_name='script',
            name='drawing_strokes',
            field=models.JSONField(blank=True, default=list, help_text="Director's Suite freehand drawing strokes"),
        ),
    ]
