# Generated by Django 5.1.15 on 2026-06-11 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0012_add_note_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='plaintext', max_length=50)),
                ('encoding', models.CharField(default='UTF-8', max_length=20)),
                ('line_endings', models.CharField(default='LF', max_length=10)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
